// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/dsnet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key-value style for vector clocks
type VectorClockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClockEntry) Reset() {
	*x = VectorClockEntry{}
	mi := &file_proto_dsnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockEntry) ProtoMessage() {}

func (x *VectorClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dsnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockEntry.ProtoReflect.Descriptor instead.
func (*VectorClockEntry) Descriptor() ([]byte, []int) {
	return file_proto_dsnet_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClockEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VectorClockEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Vector        []*VectorClockEntry    `protobuf:"bytes,5,rep,name=vector,proto3" json:"vector,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_dsnet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dsnet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_dsnet_proto_rawDescGZIP(), []int{1}
}

func (x *Envelope) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Envelope) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Envelope) GetVector() []*VectorClockEntry {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_dsnet_proto protoreflect.FileDescriptor

const file_proto_dsnet_proto_rawDesc = "" +
	"\n" +
	"\x11proto/dsnet.proto\x12\x05dsnet\"@\n" +
	"\x10VectorClockEntry\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\"\x9d\x01\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12/\n" +
	"\x06vector\x18\x05 \x03(\v2\x17.dsnet.VectorClockEntryR\x06vector\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id2C\n" +
	"\x11NetworkController\x12.\n" +
	"\x06Stream\x12\x0f.dsnet.Envelope\x1a\x0f.dsnet.Envelope(\x010\x01B#Z!github.com/distcodep7/dsnet/protob\x06proto3"

var (
	file_proto_dsnet_proto_rawDescOnce sync.Once
	file_proto_dsnet_proto_rawDescData []byte
)

func file_proto_dsnet_proto_rawDescGZIP() []byte {
	file_proto_dsnet_proto_rawDescOnce.Do(func() {
		file_proto_dsnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dsnet_proto_rawDesc), len(file_proto_dsnet_proto_rawDesc)))
	})
	return file_proto_dsnet_proto_rawDescData
}

var file_proto_dsnet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_dsnet_proto_goTypes = []any{
	(*VectorClockEntry)(nil), // 0: dsnet.VectorClockEntry
	(*Envelope)(nil),         // 1: dsnet.Envelope
}
var file_proto_dsnet_proto_depIdxs = []int32{
	0, // 0: dsnet.Envelope.vector:type_name -> dsnet.VectorClockEntry
	1, // 1: dsnet.NetworkController.Stream:input_type -> dsnet.Envelope
	1, // 2: dsnet.NetworkController.Stream:output_type -> dsnet.Envelope
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dsnet_proto_init() }
func file_proto_dsnet_proto_init() {
	if File_proto_dsnet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dsnet_proto_rawDesc), len(file_proto_dsnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dsnet_proto_goTypes,
		DependencyIndexes: file_proto_dsnet_proto_depIdxs,
		MessageInfos:      file_proto_dsnet_proto_msgTypes,
	}.Build()
	File_proto_dsnet_proto = out.File
	file_proto_dsnet_proto_goTypes = nil
	file_proto_dsnet_proto_depIdxs = nil
}
